---
- name: Tests
  hosts: ipaserver
  become: no
  gather_facts: no

  tasks:
    - name: Retrieve data from assymetric vault with a private key file.
      ipavault:
        ipaadmin_password: SomeADMINpassword
        name: asymvault
        username: user01
        private_key_file: private.pem
        state: retrieved
      register: result
    - debug:
       msg: "Data: {{ result.data }}"
